Feature/pfg82 184 documento orden venta
sjponce/brava-sales pull request #100
Opened 2024-08-31 10:36 UTC by osmar222

buenos días presento esta PR con los cambios para que el documento de la orden de venta tenga todos los campos requeridos

2024-08-31 10:43 UTC, osmar222 commented
no estaba al dia con develop, ahora si deberia estar bien para aprobar la PR

2024-08-31 16:34 UTC, sjponce requested changes

2024-08-31 16:34 UTC, sjponce commented on backend/package.json
> +		"date-fns": "^3.6.0",
Eliminar

2024-08-31 16:34 UTC, sjponce commented on backend/src/controllers/middlewaresControllers/createDocMiddleware/docSalesOrder.js
> +        orderDate: format(new Date(salesOrderData.orderDate), 'dd/MM/yyyy'),
No me uses una librería para formatear la fecha, usa la función de formato que ya estamos usando en utils, si no está en el backend búscala del frontend y copiala

2024-09-02 20:07 UTC, osmar222 commented on backend/package.json
> +		"date-fns": "^3.6.0",
borrado

2024-09-02 20:07 UTC, osmar222 commented on backend/src/controllers/middlewaresControllers/createDocMiddleware/docSalesOrder.js
> +        orderDate: format(new Date(salesOrderData.orderDate), 'dd/MM/yyyy'),
listo hice eso

2024-09-02 21:46 UTC, sjponce approved these changes

2024-09-02 21:46 UTC, merged