PFG82-193-143: Get products/Get product details
sjponce/brava-sales pull request #76
Opened 2024-07-03 22:30 UTC by ebert-alem

![image](https://github.com/sjponce/brava-sales/assets/69051941/2d3d7602-9ce3-4020-b14e-7b79d9bccdea)

![image](https://github.com/sjponce/brava-sales/assets/69051941/0511957d-a5ce-4e4b-9934-4ba025f548a7)

2024-07-04 12:50 UTC, sjponce requested changes

2024-07-04 12:50 UTC, sjponce commented on frontend/jsconfig.json
> +    "jsx": "react",
porque agregaste este cambio?

2024-07-04 12:50 UTC, sjponce commented on frontend/src/pages/private/products/components/ModalProductDetails.jsx
> +export default ModalProductDetails;
Unitest, everywhere

2024-07-05 19:49 UTC, ebert-alem commented on frontend/jsconfig.json
> +    "jsx": "react",
alguna dependencia será que la agrego.

2024-07-05 20:43 UTC, sjponce commented
Sacalo si no sabes para que es

El vie, 5 de jul de 2024, 16:49, Ebert Aleman ***@***.***>
escribió:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In frontend/jsconfig.json
> <https://github.com/sjponce/brava-sales/pull/76#discussion_r1667091484>:
>
> > @@ -1,5 +1,6 @@
>  {
>    "compilerOptions": {
> +    "jsx": "react",
>
> alguna dependencia será que la agrego.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sjponce/brava-sales/pull/76#discussion_r1667091484>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKOEJJDYBTZ5ZOWS7VILF23ZK32ETAVCNFSM6AAAAABKKNE4NSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNRRGE4DMMBZG4>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-07-12 21:08 UTC, merged