PFG82-59 Ver cliente
sjponce/brava-sales pull request #77
Opened 2024-07-04 18:08 UTC by osmar222

Se puede ver la tabla con los clientes :D

2024-07-04 18:36 UTC, sjponce commented
Esta roto el pipeline, fijate el error y commitea el fix

2024-07-04 19:43 UTC, sjponce requested changes
Nashe PR

2024-07-04 19:43 UTC, sjponce commented on frontend/src/pages/private/clients/components/DataTableClients.jsx
> +      field: 'razonSocial',
Usemos nombres en ingles please. 
tenemos name y razon social

2024-07-04 19:43 UTC, sjponce commented on frontend/src/pages/private/clients/components/DataTableClients.jsx
> +          return `${address[0]} ${address[1]}, ${address[5]}`;
metele una funcion en un archivito utils que tenga una funcion para esto qeu devuelva esta forma de visualizar la address, la vamos a usar en mas lados.

2024-07-04 19:43 UTC, sjponce commented on frontend/src/pages/private/clients/components/DataTableClients.jsx
> +          return `${address[0]} ${address[1]}, ${address[5]}`;
Seria mejor qeu la dirección se guarde como objeto y no array porque no se peude saber que es cada opcion del array, 

address = {
     city
     street
     number
     ....
}

2024-07-04 19:43 UTC, sjponce commented on frontend/src/pages/private/clients/components/DataTableClients.jsx
> +    dispatch(crud.listAll({ entity: 'user' }));
este no es un user es un client, cambia la entidad porque vas guardar los clientes en la tabla de vendedores(user actualmente) y en el get estas recibiendo vendedores y clientes
![image](https://github.com/sjponce/brava-sales/assets/43795620/efa9a5eb-f149-41fe-ad45-dd2f273eebb9)

2024-07-04 19:43 UTC, sjponce commented on frontend/src/pages/private/clients/components/DataTableClients.jsx
> +      .filter((item) => item.role === 'Client')
Aca si cambias el api no ahce falta el filter

2024-07-13 22:52 UTC, osmar222 commented on frontend/src/pages/private/clients/components/DataTableClients.jsx
> +      field: 'razonSocial',
listo todo en ingles

2024-07-13 23:06 UTC, sjponce approved these changes

2024-07-13 23:11 UTC, sjponce approved these changes

2024-07-19 18:26 UTC, merged